export * from './bank.model';
export * from './city.model';
export * from './country.model';
export * from './state.model';
export * from './page-options';
export * from './specialization.model';
export * from './sub-specialization.model';
export * from './resource.model';
export * from './tp-table-options.interface'
export * from './tp-table-paging.interface';
export * from './tp-table.types'
